from app.routes.auth_routes import auth_bp
from app.routes.transaction_routes import transaction_bp
from app.routes.dashboard_routes import dashboard_bp
from app.routes.page_routes import page_bp
from app.routes.category_routes import category_bp
from app.routes.goal_routes import goal_bp
from app.routes.upload_routes import upload_bp
from app.routes.profile_routes import profile_bp
from app.routes.analytics_routes import analytics_bp
from app.routes.simulator_routes import simulator_bp
from app.routes.recurring_routes import recurring_bp
from app.routes.prediction_routes import prediction_bp
from app.routes.budget_routes import budget_bp
from app.routes.anomaly_routes import anomaly_bp
from app.routes.insight_routes import insight_bp
from app.routes.narrative_routes import narrative_bp